project:
  type: website
  output-dir: docs

website:
  title: "TU Chemnitz | Methods Competency Center"
  subtitle: "MethodenKompetenzZentrum"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
    left: 
      - text: "Home"
        file: index.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    citations-hover: true
    footnotes-hove: true 



